# Generated by Django 4.1 on 2022-10-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('imo', models.CharField(max_length=10)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField(blank=True)),
                ('service_time', models.FloatField()),
                ('ship_type', models.CharField(max_length=30)),
                ('dwt', models.FloatField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_info.port')),
            ],
        ),
    ]
