# Generated by Django 4.1 on 2022-10-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipcalls',
            name='date_in',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipcalls',
            name='date_out',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
