# Generated by Django 4.1 on 2022-11-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0002_alter_shipcalls_date_in_alter_shipcalls_date_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='sea',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
