# Generated by Django 5.2.5 on 2025-09-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0003_port_sea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShipTypeToShipCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_info.shipcalls')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships_info.shiptypes')),
            ],
        ),
    ]
