# Generated by Django 5.2.5 on 2025-09-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0004_shiptypes_shiptypetoshipcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('deadweight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
            ],
        ),
    ]
