# Generated by Django 5.2.5 on 2025-09-27 12:49

import django.db.models.deletion
import ships_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0006_auto_20250925_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipdata',
            name='ship_type',
            field=models.ForeignKey(default=ships_info.models.ShipTypes.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='ships_info.shiptypes'),
        ),
    ]
