# Generated by Django 5.2.5 on 2025-09-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0008_auto_20250927_1256'),
    ]

    operations = [
    ]
