# Generated by Django 5.2.5 on 2025-09-27 16:04

import django.db.models.deletion
import ships_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0009_auto_20250927_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionsCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=20)),
                ('a_value', models.FloatField()),
                ('ship_type', models.ForeignKey(default=ships_info.models.ShipTypes.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='ships_info.shiptypes')),
            ],
        ),
        migrations.CreateModel(
            name='PiancShips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_class_name', models.CharField(max_length=150)),
                ('deadweight', models.FloatField()),
                ('length', models.FloatField()),
                ('depth', models.FloatField()),
                ('container_capacity', models.FloatField(blank=True, null=True)),
                ('ship_type', models.ForeignKey(default=ships_info.models.ShipTypes.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='ships_info.shiptypes')),
            ],
        ),
    ]
