# Generated by Django 5.2.5 on 2025-09-27 16:04

from django.db import migrations

def save_data(apps, schema_editor):
    ships_dim_c = apps.get_model("ships_info", "DimensionsCorrelation") 
    Shipstype = apps.get_model("ships_info", "ShipTypes")
    tanker = Shipstype.objects.get(name="Танкер")
    containership = Shipstype.objects.get(name='Контейнеровоз')
    bulker = Shipstype.objects.get(name='Балкер')
    lng_carrier = Shipstype.objects.get(name='Газовоз')
    data = [
        [tanker, "length", 5.466822557],
        [tanker, "width", 13.01485505],
        [tanker, "depth", 0.340261701],
        
        [containership, "length", 6.505346189],
        [containership, "width", 0.943858862],
        [containership, "depth", 0.339078155],
        
        [bulker, "length", 5.334228577],
        [bulker, "width", 0.817837974],
        [bulker, "depth", 0.325971149],

        [lng_carrier, "length", 5.334228577],
        [lng_carrier, "width", 0.817837974],
        [lng_carrier, "depth", 0.325971149],
    ]   
    for d in data:
        new_c = ships_dim_c(
            ship_type = d[0],
            parameter = d[1],
            a_value = d[2]
        )
        new_c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0010_dimensionscorrelation_piancships'),
    ]

    operations = [
        migrations.RunPython(save_data)
    ]
