# Generated by Django 5.2.5 on 2025-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0012_auto_20250927_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='piancships',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
