# Generated by Django 5.2.5 on 2025-09-27 16:36

from django.db import migrations

def save_data(apps, schema_editor):
    pianc_ships = apps.get_model("ships_info", "PiancShips") 
    Shipstype = apps.get_model("ships_info", "ShipTypes")
    tanker = Shipstype.objects.get(name="Танкер")
    containership = Shipstype.objects.get(name='Контейнеровоз')
    bulker = Shipstype.objects.get(name='Балкер')
    lng_carrier = Shipstype.objects.get(name='Газовоз')
    list_of_pianc_ships = pianc_ships.objects.all()
    for p_s in list_of_pianc_ships:
        p_s.delete()
    data = [ 
        [tanker, 'ULCC', 450000, 380, 68, 24.5],
        [tanker, 'VLCC', 320000, 333, 60, 22.6],
        [tanker, 'VLCC', 300000, 333, 60, 21.6],
        [tanker, 'VLCC', 280000, 333, 60, 20.4],
        [tanker, 'VLCC', 193000, 288, 50, 19.6],
        [tanker, 'VLCC', 165000, 274, 50, 17.1],
        [tanker, 'Suezmax', 150000, 274, 50, 16],
        [tanker, 'Aframax', 115000, 250, 44, 14.8],
        [tanker, 'Aframax', 100000, 248, 43, 13.5],
        [tanker, 'Coastal/Panamax', 70000, 228, 32.2, 13.6],
        [tanker, 'Coastal/Panamax', 60000, 214, 32.2, 12.3],
        [tanker, 'Long Range 1', 75000, 229, 32.2, 14.7],
        [tanker, 'Medium Range 2', 50000, 183, 32.2, 12.9],
        [tanker, 'Medium Range 1', 40000, 182, 32.2, 11],
        [tanker, 'Medium Range 1', 30000, 177, 29, 9.5],
        [tanker, 'General Purpose', 20000, 164, 23, 8.5],
        [tanker, 'General Purpose', 10000, 120, 20, 7.8],
        [tanker, 'General Purpose', 5000, 105, 16, 6.4],
        [tanker, 'General Purpose', 3000, 89, 13, 5.5],
        [bulker, 'Chinamax', 400000, 360, 65, 23],
        [bulker, 'VLOC', 325000, 333, 60, 22.7],
        [bulker, 'VLOC', 300000, 327, 55, 21.6],
        [bulker, 'VLOC', 250000, 330, 57, 18.1],
        [bulker, 'Large Cape', 230000, 325, 52.5, 18.2],
        [bulker, 'Cape', 200000, 300, 50, 18],
        [bulker, 'Cape', 185000, 290, 47, 18],
        [bulker, 'Cape', 170000, 291, 45, 17.8],
        [bulker, 'Small Cape', 150000, 273, 43, 17.4],
        [bulker, 'Mini Cape', 120000, 260, 43, 14.5],
        [bulker, 'Post Panamax (wide)', 100000, 250, 43, 13.2],
        [bulker, 'Post Panamax (narrow)', 100000, 240, 38, 14.5],
        [bulker, 'Post Panamax', 85000, 229, 38, 13.5],
        [bulker, 'Panamax', 80000, 229, 32.2, 14.5],
        [bulker, 'Panamax', 70000, 225, 32.2, 13.3],
        [bulker, 'Supramax', 60000, 200, 32.2, 13],
        [bulker, 'Handymax', 50000, 190, 32.2, 12],
        [bulker, 'Handymax', 40000, 180, 30, 10.7],
        [bulker, 'Handy size', 30000, 179, 28, 9.8],
        [bulker, 'Handy size', 20000, 155, 23.7, 9.2],
        [bulker, 'Handy size', 10000, 114, 19.4, 8],
        [bulker, '-', 5000, 96, 16, 6],
        [lng_carrier, 'LNG-QMax', 155000, 345, 55, 13.7],
        [lng_carrier, 'LNG-QMax', 130000, 345, 53.8, 12.2],
        [lng_carrier, 'LNG-Qflex', 120000, 315, 50, 13.6],
        [lng_carrier, 'LNG-Qflex', 107000, 315, 50, 12.5],
        [lng_carrier, 'LNG New Panamax', 98000, 296, 46.4, 12.8],
        [lng_carrier, 'LNG New Panamax', 90000, 289, 45.6, 12.5],
        [lng_carrier, 'LNG Conventional', 80000, 289, 48, 12.3],
        [lng_carrier, 'LNG Conventional', 70000, 274, 47.2, 11.8],
        [lng_carrier, 'LNG Conventional', 40000, 220, 35, 10],
        [lng_carrier, 'LNG Small', 11000, 151, 28, 7.7],
        [lng_carrier, 'Combination Gas/LPG', 20000, 180, 26.6, 9.4],
        [lng_carrier, 'Combination Gas/LPG', 10000, 137, 19.8, 8.3],
        [lng_carrier, 'LPG-Very Large Gas Carrier', 64000, 228, 36, 13.6],
        [lng_carrier, 'LPG-Very Large Gas Carrier', 50000, 230, 36.6, 10.9],
        [lng_carrier, 'LPG-Large Gas Carrier', 43000, 205, 32.2, 11.9],
        [lng_carrier, 'LPG-Medium Gas Carrier', 30000, 182, 29.4, 10.4],
        [lng_carrier, 'LPG-Medium Gas Carrier', 22000, 160, 25.6, 10.9],
        [lng_carrier, 'LPG-Small Gas Carrier', 10000, 120, 19.8, 8.8],
        [lng_carrier, 'LPG-Small Gas Carrier', 5000, 106, 17.6, 5.8],
        [lng_carrier, 'LPG-Small Gas Carrier', 3000, 96, 16.4, 4.5],
        [lng_carrier, 'LPG-Small Gas Carrier', 1000, 65, 11, 4.2],
        [containership, 'Post Panamax', 240000, 400, 61.2, 17, 24000],
        [containership, 'Post Panamax', 225000, 400, 61, 16.5, 23700],
        [containership, 'Post Panamax', 200000, 400, 58.8, 16, 20000],
        [containership, 'Post Panamax', 185000, 400, 54, 16, 19000],
        [containership, 'Post Panamax', 165000, 366, 51.2, 16, 15000],
        [containership, 'Post Panamax', 150000, 369, 51, 15.6, 14000],
        [containership, 'Post Panamax', 130000, 348, 45.2, 15.5, 11500],
        [containership, 'Post Panamax', 120000, 337, 48.2, 15.5, 10000],
        [containership, 'Post Panamax', 110000, 300, 48.2, 14.5, 9000],
        [containership, 'Post Panamax', 100000, 334, 42.8, 14.5, 8700],
        [containership, 'Post Panamax', 90000, 316, 45.6, 14.5, 8500],
        [containership, 'Post Panamax', 80000, 304, 40, 14, 6800],
        [containership, 'Post Panamax', 70000, 280, 40.3, 14, 6000],
        [containership, 'Post Panamax', 65000, 255, 37.3, 13.9, 5500],
        [containership, 'Post Panamax', 60000, 249, 37.4, 13.5, 5200],
        [containership, 'Post Panamax', 52000, 228, 37.3, 12.5, 4300],
        [containership, 'Panamax', 65000, 294, 32.26, 13.5, 5000],
        [containership, 'Panamax', 60000, 275, 32.26, 13.5, 5000],
        [containership, 'Panamax', 55000, 261, 32.26, 13, 4500],
        [containership, 'Panamax', 50000, 261, 32.26, 12.6, 4200],
        [containership, 'Panamax', 45000, 247, 32.26, 12.3, 3500],
        [containership, 'Panamax', 40000, 233, 32.26, 11.8, 3200],
        [containership, 'Panamax', 35000, 210, 30.2, 11.5, 2800],
        [containership, 'Panamax', 30000, 199, 30.2, 11.2, 2500],
        [containership, 'Panamax', 25000, 185, 30, 9.5, 2200],
        [containership, 'Panamax', 20000, 170, 25, 9.5, 1500],
        [containership, 'Panamax', 15000, 147, 25, 9, 1200],
        [containership, 'Panamax', 10000, 140, 20.5, 7.5, 800]
    ]
    for d in data:
        new_pianc_ship = pianc_ships(
            ship_type = d[0],
            ship_class_name = d[1],
            deadweight = d[2],
            length = d[3],
            width = d[4],
            depth = d[5]
        )
        if len(d) > 6:
            new_pianc_ship.container_capacity = d[6]
        new_pianc_ship.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0013_piancships_width'),
    ]

    operations = [
        migrations.RunPython(save_data)
    ]
