# Generated by Django 5.2.5 on 2025-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0014_auto_20250927_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiptypes',
            name='eng_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
