# Generated by Django 5.2.5 on 2025-10-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships_info', '0015_shiptypes_eng_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipcalls',
            name='port',
        ),
        migrations.RemoveField(
            model_name='shiptypetoshipcall',
            name='ship_call',
        ),
        migrations.RemoveField(
            model_name='shiptypetoshipcall',
            name='ship_type',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='ShipCalls',
        ),
        migrations.DeleteModel(
            name='ShipTypeToShipCall',
        ),
    ]
